name: business_module
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  data_module:
    path: ../data_module
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  injectable_generator:
  build_runner:
