name: data_module
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.5
